#!/bin/bash
case $1 in
    run|start)
    clear
    echo "  ____   __     __   ____    ____       _____                                     ";
    echo " |  _ \  \ \   / /  / __ \  |  _ \     / ____|                                    ";
    echo " | |_) |  \ \_/ /  | |  | | | |_) |   | (___     ___   _ __  __   __   ___   _ __ ";
    echo " |  _ <    \   /   | |  | | |  _ <     \___ \   / _ \ | '__| \ \ / /  / _ \ | '__|";
    echo " | |_) |    | |    | |__| | | |_) |    ____) | |  __/ | |     \ V /  |  __/ | |   ";
    echo " |____/     |_|     \____/  |____/    |_____/   \___| |_|      \_/    \___| |_|   ";
    echo "                                                                                  ";
    echo "                                                                                  ";
    echo "Starting your byob server with vrl-package"
    echo ""
    echo "Open URL in browser: ""$HOSTNAME"".local:5000"
    sudo systemctl start byob
    ;;
    halt|stop)
    clear
    echo "  ____   __     __   ____    ____       _____                                     ";
    echo " |  _ \  \ \   / /  / __ \  |  _ \     / ____|                                    ";
    echo " | |_) |  \ \_/ /  | |  | | | |_) |   | (___     ___   _ __  __   __   ___   _ __ ";
    echo " |  _ <    \   /   | |  | | |  _ <     \___ \   / _ \ | '__| \ \ / /  / _ \ | '__|";
    echo " | |_) |    | |    | |__| | | |_) |    ____) | |  __/ | |     \ V /  |  __/ | |   ";
    echo " |____/     |_|     \____/  |____/    |_____/   \___| |_|      \_/    \___| |_|   ";
    echo "                                                                                  ";
    echo "                                                                                  ";
    echo "Halting your byob server with vrl-package"
    sudo systemctl stop byob
    ;;
    status)
    clear
    echo "  ____   __     __   ____    ____       _____                                     ";
    echo " |  _ \  \ \   / /  / __ \  |  _ \     / ____|                                    ";
    echo " | |_) |  \ \_/ /  | |  | | | |_) |   | (___     ___   _ __  __   __   ___   _ __ ";
    echo " |  _ <    \   /   | |  | | |  _ <     \___ \   / _ \ | '__| \ \ / /  / _ \ | '__|";
    echo " | |_) |    | |    | |__| | | |_) |    ____) | |  __/ | |     \ V /  |  __/ | |   ";
    echo " |____/     |_|     \____/  |____/    |_____/   \___| |_|      \_/    \___| |_|   ";
    echo "                                                                                  ";
    echo "                                                                                  ";
    sudo systemctl status byob
    ;;
    enable)
    sudo systemctl enable byob
    ;;
    disable)
    sudo systemctl disable byob
    ;;
    reload)
    sudo systemctl daemon-reload
    ;;
    edit)
    sudo nano /etc/systemd/system/byob.service
    ;;
    follow)
    clear
    echo "  ____   __     __   ____    ____       _____                                     ";
    echo " |  _ \  \ \   / /  / __ \  |  _ \     / ____|                                    ";
    echo " | |_) |  \ \_/ /  | |  | | | |_) |   | (___     ___   _ __  __   __   ___   _ __ ";
    echo " |  _ <    \   /   | |  | | |  _ <     \___ \   / _ \ | '__| \ \ / /  / _ \ | '__|";
    echo " | |_) |    | |    | |__| | | |_) |    ____) | |  __/ | |     \ V /  |  __/ | |   ";
    echo " |____/     |_|     \____/  |____/    |_____/   \___| |_|      \_/    \___| |_|   ";
    echo "                                                                                  ";
    echo "                                                                                  ";
    journalctl -f _SYSTEMD_UNIT=byob.service
    ;;
    help)
        echo "Commands around byob:"
        echo "byob help - This help page"
        echo "byob start - Start your byob"
        echo "byob stop - Stop your byob"
        echo "byob status - Get byob status"
        echo "byob follow - Follow your byob log and server"
        echo "byob enable - Enable your byob so it start on server bootup"
        echo "byob diable - Diable your byob from starting on server bootup"
        echo ""
        ;;
    *) echo "> Use 'byob help' to get help";;
esac
